version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: student_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: student_management
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  

volumes:
  pg_data: